### ISSUE TITLE
Use config file as well as command line options

### ISSUE THREAD

**Issue by mathuin** [TinyMultiplayerBot/GMRHC#1]
mythmon/gmrjs has defined a configuration file for Giant Multiplayer Robot clients.  It would be awesome if you were to use the same configuration file.  Currently only keys are supported, but save dirs would be a smart thing to add.

**Comment by justinnoah** [comment]
Great idea! @mythmon and I talked and have decided on a mutual config located at ~/.gmrrc with the format of (if not very close to) an ini file with no section header and the following pairs:

auth_key=&lt;your auth key>
save_path=&lt;hotseat save location>
auto_download=false
auto_upload=false

**Comment by mathuin** [comment]
Looks great to me!  The key (hee) here is that you guys work together so we can use either client and have it use the same parameters.  I recommend you guys use a default value for save_path based on operating system (Linux under ~/.local, Windows wherever) and don't forget to make the new keys command-line options too!
